<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookingSeeder extends Seeder
{
    public function run(): void
    {
        $dataUser = [
            [
                'id' => 1,
                'name' => 'Chan Manet',
                'local_name' => 'រ័ត្ន អង្គារម៉ាណែត',
                'dob' => '2005-03-03',
                'gender' => 1,
                'phone_number' => '1234567890',
                'email' => 'chanmanet@example.com',
                'user_id' => 3,
                'doctor_id' => 2,
                'sub_service_id' => null,
                'appointment_time' => '2025-03-25 10:00:00',
                'description' => 'Consultation for general health checkup.',
                'file' => null,
                'booking_status' => 0,
                'is_complete' => false,
                'cancelled_at' => null,
                'service_type' => 0,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 2,
                'name' => 'Sokha Serey',
                'local_name' => 'សុខា ស្រី',
                'dob' => '1990-07-15',
                'gender' => 2,
                'phone_number' => '2345678901',
                'email' => 'sokhaserey@example.com',
                'user_id' => 3,
                'doctor_id' => null,
                'sub_service_id' => 1,
                'service_type' => 1,
                'appointment_time' => '2025-03-21 11:30:00',
                'description' => 'Consultation for skin allergy treatment.',
                'file' => null,
                'booking_status' => 1,
                'is_complete' => false,
                'cancelled_at' => null,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 3,
                'name' => 'Vannak Sovath',
                'local_name' => 'វណ្ណាក់ សុវត្ថ',
                'dob' => '1995-10-10',
                'gender' => 1,
                'phone_number' => '3456789012',
                'email' => 'vannaksovath@example.com',
                'user_id' => 3,
                'doctor_id' => null,
                'sub_service_id' => 2,
                'service_type' => 2,
                'appointment_time' => '2025-03-22 09:00:00',
                'description' => 'Physical therapy consultation.',
                'file' => null,
                'booking_status' => 0,
                'is_complete' => false,
                'cancelled_at' => null,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 4,
                'name' => 'Srey Leak',
                'local_name' => 'ស្រី លក្ខ',
                'dob' => '1992-12-05',
                'gender' => 2,
                'phone_number' => '4567890123',
                'email' => 'sreyleak@example.com',
                'user_id' => 3,
                'doctor_id' => 2,
                'sub_service_id' => null,
                'service_type' => 0,
                'appointment_time' => '2025-03-25 15:00:00',
                'description' => 'Check-up for eye vision.',
                'file' => null,
                'booking_status' => 1,
                'is_complete' => false,
                'cancelled_at' => null,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 5,
                'name' => 'Rithy Phin',
                'local_name' => 'រី ថី ភិន',
                'dob' => '1988-05-11',
                'gender' => 1,
                'phone_number' => '5678901234',
                'email' => 'rithyphin@example.com',
                'user_id' => 3,
                'doctor_id' => null,
                'sub_service_id' => 3,
                'service_type' => 2,
                'appointment_time' => '2025-03-24 13:30:00',
                'description' => 'Dental check-up and cleaning.',
                'file' => null,
                'booking_status' => 0,
                'is_complete' => false,
                'cancelled_at' => null,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 6,
                'name' => 'Sok Vanna',
                'local_name' => 'សុខ វណ្ណា',
                'dob' => '2000-02-20',
                'gender' => 1,
                'phone_number' => '6789012345',
                'email' => 'sokvanna@example.com',
                'user_id' => 3,
                'doctor_id' => 2,
                'sub_service_id' => null,
                'service_type' => 0,
                'appointment_time' => '2025-03-25 14:00:00',
                'description' => 'Emergency consultation for fever.',
                'file' => null,
                'booking_status' => 0,
                'is_complete' => false,
                'cancelled_at' => null,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 7,
                'name' => 'Sok Vanna',
                'local_name' => 'សុខ វណ្ណា',
                'dob' => '2000-02-20',
                'gender' => 1,
                'phone_number' => '6789012345',
                'email' => 'sokvanna@example.com',
                'user_id' => 3,
                'doctor_id' => null,
                'sub_service_id' => 1,
                'service_type' => 1,
                'appointment_time' => '2025-03-25 15:00:00',
                'description' => 'Emergency consultation.',
                'file' => 'hello.pdf',
                'booking_status' => 3,
                'is_complete' => false,
                'cancelled_at' => '2025-03-22 14:49:00',
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 8,
                'name' => 'Sok Vanna',
                'local_name' => 'សុខ វណ្ណា',
                'dob' => '2000-02-20',
                'gender' => 1,
                'phone_number' => '6789012345',
                'email' => 'sokvanna@example.com',
                'user_id' => 3,
                'doctor_id' => 2,
                'sub_service_id' => null,
                'service_type' => 0,
                'appointment_time' => '2025-03-24 8:00:00',
                'description' => 'Emergency consultation for fever.',
                'file' => null,
                'booking_status' => 2,
                'is_complete' => false,
                'cancelled_at' => null,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 9,
                'name' => 'Sok Vanna',
                'local_name' => 'សុខ វណ្ណា',
                'dob' => '2000-02-20',
                'gender' => 1,
                'phone_number' => '6789012345',
                'email' => 'sokvanna@example.com',
                'user_id' => 3,
                'doctor_id' => 2,
                'sub_service_id' => null,
                'service_type' => 0,
                'appointment_time' => '2025-03-21 10:00:00',
                'description' => 'Emergency consultation for fever.',
                'file' => null,
                'booking_status' => 2,
                'is_complete' => true,
                'cancelled_at' => null,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 10,
                'name' => 'Sok Vanna',
                'local_name' => 'សុខ វណ្ណា',
                'dob' => '2000-02-20',
                'gender' => 1,
                'phone_number' => '6789012345',
                'email' => 'sokvanna@example.com',
                'user_id' => 3,
                'doctor_id' => 2,
                'sub_service_id' => null,
                'service_type' => 0,
                'appointment_time' => '2025-03-21 8:00:00',
                'description' => 'Emergency consultation for fever.',
                'file' => null,
                'booking_status' => 2,
                'is_complete' => false,
                'cancelled_at' => null,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 11,
                'name' => 'Vannak Sovath',
                'local_name' => 'វណ្ណាក់ សុវត្ថ',
                'dob' => '1995-10-10',
                'gender' => 1,
                'phone_number' => '3456789012',
                'email' => 'vannaksovath@example.com',
                'user_id' => 3,
                'doctor_id' => null,
                'sub_service_id' => 2,
                'service_type' => 1,
                'appointment_time' => '2025-03-25 09:00:00',
                'description' => 'Physical therapy consultation.',
                'file' => null,
                'booking_status' => 0,
                'is_complete' => false,
                'cancelled_at' => null,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 12,
                'name' => 'Srey Leak',
                'local_name' => 'ស្រី លក្ខ',
                'dob' => '1992-12-05',
                'gender' => 2,
                'phone_number' => '4567890123',
                'email' => 'sreyleak@example.com',
                'user_id' => 3,
                'doctor_id' => 5,
                'sub_service_id' => null,
                'service_type' => 0,
                'appointment_time' => '2025-03-27 15:00:00',
                'description' => 'Check-up for eye vision.',
                'file' => null,
                'booking_status' => 1,
                'is_complete' => false,
                'cancelled_at' => null,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
            [
                'id' => 13,
                'name' => 'Rithy Phin',
                'local_name' => 'រី ថី ភិន',
                'dob' => '1988-05-11',
                'gender' => 1,
                'phone_number' => '5678901234',
                'email' => 'rithyphin@example.com',
                'user_id' => 5,
                'doctor_id' => null,
                'sub_service_id' => 3,
                'service_type' => 2,
                'appointment_time' => '2025-03-28 13:30:00',
                'description' => 'Dental check-up and cleaning.',
                'file' => null,
                'booking_status' => 0,
                'is_complete' => false,
                'cancelled_at' => null,
                'created_at' => \Carbon\Carbon::now(),
                'updated_at' => \Carbon\Carbon::now(),
            ],
        ];

        foreach ($dataUser as $data) {
            DB::table('bookings')->insert($data);
        }
    }

}
